# .github/workflows/ci-cd.yml
name: CI/CD Workflow

on:
  push:
    branches:
      - pypi-publish  # Triggers on pushes to the main branch
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/<your-pypi-project-name>/  # Replace with your PyPI project URL
    permissions:
      id-token: write  # Mandatory for trusted publishing
      contents: read  # Allows access to repository content (required by actions)
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Checks out your repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x  # Replace with the Python version your project requires

    - name: Install Build Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build Distributions
      run: python -m build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}  # Requires a PyPI token stored in GitHub Secrets